/* ============================================================
   CAMA'FFARE — DEFINIZIONE DEL MENU
   ============================================================
   Questo e' l'UNICO file da modificare per aggiornare il menu.
   Non serve toccare l'HTML: la pagina menu.html si costruisce da qui.

   ------------------------------------------------------------
   COME AGGIUNGERE UN PRODOTTO
   ------------------------------------------------------------
   1. Metti la foto dentro la cartella  menu/  (es. menu/arancino-ragu.jpg)
      -> formato consigliato: quadrato, 800x800 px, jpg, max ~200 KB
   2. Aggiungi una riga nell'array PRODOTTI:

        { id: 'arancino-ragu',            // identificativo unico, minuscolo, con trattini
          categoria: 'arancini',          // deve essere un id presente in CATEGORIE
          nome: 'Arancino al ragu',
          descrizione: 'Riso, ragu di carne, piselli.',
          prezzo: 3.00,                   // numero, punto decimale, senza simbolo €
          foto: 'menu/arancino-ragu.jpg', // opzionale: se manca o non esiste esce un placeholder
          tag: ['piccante'] },            // opzionale: 'vegetariano' | 'vegano' | 'piccante' | 'novita'

   3. Salva. Fine.

   NOTA: se la foto non c'e' ancora, lascia pure il campo `foto` — finche' il file
   non esiste il sito mostra automaticamente un placeholder colorato con l'icona
   della categoria. Nessun errore, nessuna immagine rotta.

   ------------------------------------------------------------
   COME AGGIUNGERE / RIORDINARE UNA CATEGORIA
   ------------------------------------------------------------
   Aggiungi o sposta un oggetto in CATEGORIE. L'ordine dell'array e' l'ordine
   con cui compaiono i filtri in alto e i gruppi nella pagina.
   ============================================================ */

/* ------------------------------------------------------------
   Menu reale del negozio: 166 voci in 22 categorie.
   Due note su come sono stati riportati i dati:
   - "Milingiana friuta" e "I patat" nel menu non hanno un nome di prodotto,
     solo l'elenco degli ingredienti: li ho numerati (Milingiana 1, I patat 1...)
     come il negozio fa gia' con "Arancino 3" o "Calzoncino 1", e l'elenco e'
     finito nella descrizione. Rinominali pure qui sotto se preferisci.
   - I tag: 'vegano' e 'novita' vengono dalle categorie del negozio,
     'piccante' dalla presenza di salamino piccante / 'nduja / peperoncino.
     Nessun piatto e' marcato 'vegetariano': andrebbe deciso voce per voce.
   ------------------------------------------------------------ */

const CATEGORIE = [
  { id: "pizze-solite",      nome: "Pizze le solite",      icona: "🍕", colore: "#ffe7e0" },
  { id: "pizze-storiche",    nome: "Pizze le storiche",    icona: "⭐", colore: "#ffe0d6" },
  { id: "pizze-bianche",     nome: "Pizze le bianche",     icona: "🤍", colore: "#f4f1ea" },
  { id: "pizze-venete",      nome: "Pizze le venete",      icona: "🦁", colore: "#e7edf9" },
  { id: "pizze-vegane",      nome: "Pizze le vegane",      icona: "🌱", colore: "#e2f3ea" },
  { id: "pizze-novita",      nome: "Pizze le novità",      icona: "✨", colore: "#fdeacd" },
  { id: "milingiana-friuta", nome: "Milingiana friuta",    icona: "🍆", colore: "#ece4f5" },
  { id: "i-patat",           nome: "I patat",              icona: "🥔", colore: "#fdf0d4" },
  { id: "calzone",           nome: "Calzone",              icona: "🌙", colore: "#fde8d8" },
  { id: "calzoncini",        nome: "Calzoncini",           icona: "🥟", colore: "#fdeacd" },
  { id: "calzoni-fritti",    nome: "Calzoni fritti",       icona: "🍳", colore: "#fbe3c8" },
  { id: "panini",            nome: "Panini alla piastra",  icona: "🥪", colore: "#f6ead9" },
  { id: "arancini",          nome: "Arancini",             icona: "🍙", colore: "#fff2d9" },
  { id: "fritti",            nome: "Fritti",               icona: "🍟", colore: "#fdf0d4" },
  { id: "pane-panelle",      nome: "Pane e panelle",       icona: "🫓", colore: "#f7edda" },
  { id: "specialita",        nome: "Specialità siciliane", icona: "🇮🇹", colore: "#e6f2e4" },
  { id: "dolci",             nome: "Dolci",                icona: "🍰", colore: "#f3e6f7" },
  { id: "pizze-dolci",       nome: "Pizze dolci",          icona: "🍫", colore: "#efe2dc" },
  { id: "bevande",           nome: "Bevande",              icona: "🥤", colore: "#e4eefb" },
  { id: "birre",             nome: "Birre",                icona: "🍺", colore: "#f6e9cf" },
  { id: "meal-deals",        nome: "Meal deals",           icona: "🎁", colore: "#e9e9ee" },
  { id: "t-shirt",           nome: "T-shirt",              icona: "👕", colore: "#e9e9ee" },
];

const PRODOTTI = [
  /* ---------------- PIZZE LE SOLITE ---------------- */
  { id: "diavola", categoria: "pizze-solite", nome: "Diavola",
    descrizione: "Pomodoro, mozzarella e salamino piccante",
    prezzo: 8.50, foto: "menu/diavola.jpg", tag: ["piccante"] },
  { id: "margherita", categoria: "pizze-solite", nome: "Margherita",
    descrizione: "Pomodoro, mozzarella dopo cottura e origano",
    prezzo: 7.00, foto: "menu/margherita.jpg" },
  { id: "bufalina", categoria: "pizze-solite", nome: "Bufalina",
    descrizione: "Pomodoro, pomodorini, basilico e dopo cottura mozzarella di bufala",
    prezzo: 9.00, foto: "menu/bufalina.jpg" },
  { id: "prosciutto-e-funghi", categoria: "pizze-solite", nome: "Prosciutto e funghi",
    descrizione: "Pomodoro, mozzarella, prosciutto cotto e funghi",
    prezzo: 9.00, foto: "menu/prosciutto-e-funghi.jpg" },
  { id: "4-formaggi", categoria: "pizze-solite", nome: "4 formaggi",
    descrizione: "Pomodoro, mozzarella, gorgonzola, brie e grana",
    prezzo: 9.00, foto: "menu/4-formaggi.jpg" },
  { id: "tonno-e-cipolla", categoria: "pizze-solite", nome: "Tonno e cipolla",
    descrizione: "Pomodoro, mozzarella, tonno e cipolla",
    prezzo: 9.00, foto: "menu/tonno-e-cipolla.jpg" },
  { id: "viennese", categoria: "pizze-solite", nome: "Viennese",
    descrizione: "Pomodoro, mozzarella e wurstel",
    prezzo: 8.50, foto: "menu/viennese.jpg" },
  { id: "prosciutto-cotto", categoria: "pizze-solite", nome: "Prosciutto cotto",
    descrizione: "Pomodoro, mozzarella e prosciutto",
    prezzo: 8.50, foto: "menu/prosciutto-cotto.jpg" },
  { id: "capricciosa", categoria: "pizze-solite", nome: "Capricciosa",
    descrizione: "Pomodoro, mozzarella, funghi, carciofi, prosciutto cotto e salamino piccante",
    prezzo: 9.00, foto: "menu/capricciosa.jpg", tag: ["piccante"] },
  { id: "vegetariana", categoria: "pizze-solite", nome: "Vegetariana",
    descrizione: "Pomodoro, mozzarella, zucchine, radicchio, melanzane, peperoni e pomodorini",
    prezzo: 9.00, foto: "menu/vegetariana.jpg" },
  { id: "boscaiola", categoria: "pizze-solite", nome: "Boscaiola",
    descrizione: "Pomodoro, mozzarella, funghi champignon, funghi porcini e funghi chiodini",
    prezzo: 9.50, foto: "menu/boscaiola.jpg" },
  { id: "capricciosa-siciliana", categoria: "pizze-solite", nome: "Capricciosa siciliana",
    descrizione: "Pomodoro, mozzarella, funghi, carciofi, piselli, uovo sodo e prosciutto cotto",
    prezzo: 9.50, foto: "menu/capricciosa-siciliana.jpg" },
  { id: "romana", categoria: "pizze-solite", nome: "Romana",
    descrizione: "Pomodoro, mozzarella, capperi, acciughe, olive nere al forno dopo cottura e origano",
    prezzo: 8.50, foto: "menu/romana.jpg" },
  { id: "funghi", categoria: "pizze-solite", nome: "Funghi",
    descrizione: "Pomodoro, mozzarella e funghi",
    prezzo: 8.00, foto: "menu/funghi.jpg" },
  { id: "marinara", categoria: "pizze-solite", nome: "Marinara",
    descrizione: "Pomodoro e aglio",
    prezzo: 5.00, foto: "menu/marinara.jpg" },
  { id: "calzone", categoria: "pizze-solite", nome: "Calzone",
    descrizione: "Mozzarella, funghi, carciofi, prosciutto cotto e dopo cottura salsa di pomodoro",
    prezzo: 9.00, foto: "menu/calzone.jpg" },

  /* ---------------- PIZZE LE STORICHE ---------------- */
  { id: "a-carusa", categoria: "pizze-storiche", nome: "A'carusa",
    descrizione: "Pomodoro, mozzarella, gorgonzola, cipolla e salamino",
    prezzo: 11.00, foto: "menu/a-carusa.jpg" },
  { id: "u-figghiu", categoria: "pizze-storiche", nome: "U'figghiu",
    descrizione: "Pomodoro, dopo cottura mozzarella di bufala, panna dolce, pistacchio e pancetta",
    prezzo: 11.50, foto: "menu/u-figghiu.jpg" },
  { id: "a-vucciria", categoria: "pizze-storiche", nome: "A'vucciria",
    descrizione: "Pomodoro, aglio, sale, pepe, olio di oliva, dopo cottura burrata, pesto di basilico e olio di tartufo",
    prezzo: 11.00, foto: "menu/a-vucciria.jpg" },
  { id: "u-scunchiurutu", categoria: "pizze-storiche", nome: "U'scunchiurutu",
    descrizione: "Pomodoro, mozzarella, dopo cottura burrata, pomodoro condito e pancetta",
    prezzo: 12.00, foto: "menu/u-scunchiurutu.jpg" },
  { id: "a-fimminedda", categoria: "pizze-storiche", nome: "A'fimminedda",
    descrizione: "Pomodoro, mozzarella, ricotta, zucchine e dopo cottura speck",
    prezzo: 10.50, foto: "menu/a-fimminedda.jpg" },
  { id: "a-cama-ffare", categoria: "pizze-storiche", nome: "A'cama'ffare",
    descrizione: "Pomodoro, mozzarella, formaggio primo sale, pomodori secchi, salsiccia, olive nere e dopo cottura basilico",
    prezzo: 10.50, foto: "menu/a-cama-ffare.jpg" },
  { id: "a-babba", categoria: "pizze-storiche", nome: "A'babba",
    descrizione: "Pomodoro, mozzarella, stracchino, pomodorini secchi e prosciutto cotto",
    prezzo: 10.00, foto: "menu/a-babba.jpg" },
  { id: "u-mafiusu", categoria: "pizze-storiche", nome: "U'mafiusu",
    descrizione: "Pomodoro, mozzarella, gorgonzola, peperoni e dopo cottura pancetta",
    prezzo: 10.00, foto: "menu/u-mafiusu.jpg" },
  { id: "u-spacchiusu", categoria: "pizze-storiche", nome: "U'spacchiusu",
    descrizione: "Pomodoro, mozzarella, caciocavallo, salsiccia, olive nere al forno, peperoni e olio piccante",
    prezzo: 11.50, foto: "menu/u-spacchiusu.jpg", tag: ["piccante"] },
  { id: "u-fitusu", categoria: "pizze-storiche", nome: "U'fitusu",
    descrizione: "Pomodoro, mozzarella, crema di formaggi, dopo cottura pecorino, rucola e prosciutto cotto",
    prezzo: 10.50, foto: "menu/u-fitusu.jpg" },
  { id: "a-pilusa", categoria: "pizze-storiche", nome: "A'pilusa",
    descrizione: "Pomodoro, mozzarella, scamorza, asparagi e dopo cottura speck",
    prezzo: 10.50, foto: "menu/a-pilusa.jpg" },
  { id: "u-pecuraro", categoria: "pizze-storiche", nome: "U'pecuraro",
    descrizione: "Pomodoro, mozzarella, melanzane, pomodoro condito e dopo cottura ricotta salata a scaglie",
    prezzo: 9.50, foto: "menu/u-pecuraro.jpg" },
  { id: "a-strammata", categoria: "pizze-storiche", nome: "A'strammata",
    descrizione: "Pomodoro, zucchine, salamino, dopo cottura mozzarella di bufala e origano",
    prezzo: 11.50, foto: "menu/a-strammata.jpg" },
  { id: "u-cannavazzu", categoria: "pizze-storiche", nome: "U'cannavazzu",
    descrizione: "Pomodoro, mozzarella, crema ai formaggi, salsiccia e radicchio",
    prezzo: 10.50, foto: "menu/u-cannavazzu.jpg" },
  { id: "a-cammurria", categoria: "pizze-storiche", nome: "A'cammurria",
    descrizione: "Pomodoro, mozzarella, funghi, carciofi, olive nere, uovo, wurstel, salamino e prosciutto cotto",
    prezzo: 12.00, foto: "menu/a-cammurria.jpg" },
  { id: "futtitinni", categoria: "pizze-storiche", nome: "Futtitinni",
    descrizione: "Pomodoro, mozzarella, spinaci, salamino, patè di olive e dopo cottura burrata",
    prezzo: 12.00, foto: "menu/futtitinni.jpg" },
  { id: "u-picciriddu", categoria: "pizze-storiche", nome: "U'picciriddu",
    descrizione: "Pomodoro, mozzarella, acciughe e salamino",
    prezzo: 9.00, foto: "menu/u-picciriddu.jpg" },
  { id: "a-tumpulata", categoria: "pizze-storiche", nome: "A'tumpulata",
    descrizione: "Pomodoro, mozzarella, stracchino, melanzane e dopo cottura porchetta",
    prezzo: 10.50, foto: "menu/a-tumpulata.jpg" },
  { id: "a-minchiata", categoria: "pizze-storiche", nome: "A'minchiata",
    descrizione: "Pomodoro, mozzarella, tonno, olive taggiasche e dopo cottura mozzarella di bufala",
    prezzo: 10.00, foto: "menu/a-minchiata.jpg" },
  { id: "u-beddu", categoria: "pizze-storiche", nome: "U'beddu",
    descrizione: "Pomodoro, mozzarella dopo cottura, funghi, rucola, prosciutto crudo e olio di tartufo",
    prezzo: 11.50, foto: "menu/u-beddu.jpg" },
  { id: "a-zzita", categoria: "pizze-storiche", nome: "A'zzita",
    descrizione: "Pomodoro, mozzarella, brie, carciofi e dopo cottura bresaola",
    prezzo: 11.00, foto: "menu/a-zzita.jpg" },
  { id: "a-cucuzza", categoria: "pizze-storiche", nome: "A'cucuzza",
    descrizione: "Pomodoro, mozzarella, scamorza, zucchine e dopo cottura sfilacci di cavallo",
    prezzo: 10.50, foto: "menu/a-cucuzza.jpg" },
  { id: "u-cuppino", categoria: "pizze-storiche", nome: "U'cuppino",
    descrizione: "Pomodoro, mozzarella, gorgonzola, tonno, olive verdi e funghi chiodini",
    prezzo: 10.50, foto: "menu/u-cuppino.jpg" },
  { id: "a-strafalaria", categoria: "pizze-storiche", nome: "A'strafalaria",
    descrizione: "Pomodoro al basilico, carciofi, olive taggiasche, pomodoro secco e dopo cottura mozzarella di bufala",
    prezzo: 12.00, foto: "menu/a-strafalaria.jpg" },

  /* ---------------- PIZZE LE BIANCHE ---------------- */
  { id: "a-siciliana", categoria: "pizze-bianche", nome: "A'Siciliana",
    descrizione: "Mozzarella, melanzane fritte, dopo cottura pecorino, pomodorino caramellato e pesto di basilico",
    prezzo: 14.00, foto: "menu/a-siciliana.jpg" },
  { id: "agrigentina", categoria: "pizze-bianche", nome: "Agrigentina",
    descrizione: "Mozzarella, pesto, philadelphia e dopo cottura bresaola",
    prezzo: 11.00, foto: "menu/agrigentina.jpg" },
  { id: "a-carrapipana", categoria: "pizze-bianche", nome: "A'carrapipana",
    descrizione: "Mozzarella, gorgonzola, pomodori secchi, dopo cottura pistacchio e mortadella",
    prezzo: 12.00, foto: "menu/a-carrapipana.jpg" },
  { id: "a-catanisa", categoria: "pizze-bianche", nome: "A'catanisa",
    descrizione: "Mozzarella, crema di formaggi, dopo cottura pistacchio, rucola e sfilacci di cavallo",
    prezzo: 12.00, foto: "menu/a-catanisa.jpg" },
  { id: "a-innisa", categoria: "pizze-bianche", nome: "A'innisa",
    descrizione: "Mozzarella, ricotta, dopo cottura prosciutto crudo, rucola e olio di tartufo",
    prezzo: 12.00, foto: "menu/a-innisa.jpg" },
  { id: "a-missinisa", categoria: "pizze-bianche", nome: "A'missinisa",
    descrizione: "Mozzarella, crema di zucca, radicchio, melanzane e brie",
    prezzo: 11.00, foto: "menu/a-missinisa.jpg" },
  { id: "a-nissena", categoria: "pizze-bianche", nome: "A'nissena",
    descrizione: "Mozzarella, pancetta, patate al forno e dopo cottura uovo",
    prezzo: 10.50, foto: "menu/a-nissena.jpg" },
  { id: "a-palermitana", categoria: "pizze-bianche", nome: "A'palermitana",
    descrizione: "Mozzarella, formaggio primo sale, spinaci, acciughe e olive nere al forno",
    prezzo: 11.50, foto: "menu/a-palermitana.jpg" },
  { id: "a-ragusana", categoria: "pizze-bianche", nome: "A'ragusana",
    descrizione: "Mozzarella, provola affumicata, salsiccia, funghi porcini e dopo cottura basilico",
    prezzo: 11.50, foto: "menu/a-ragusana.jpg" },
  { id: "a-siracusana", categoria: "pizze-bianche", nome: "A'siracusana",
    descrizione: "Mozzarella, pomodorini, cipolla, olive taggiasche, dopo cottura feta fresca, cetrioli e basilico",
    prezzo: 10.00, foto: "menu/a-siracusana.jpg" },
  { id: "a-trapanisa", categoria: "pizze-bianche", nome: "A'trapanisa",
    descrizione: "Mozzarella, gamberetti, funghi chiodini, mais, rucola e panna",
    prezzo: 12.00, foto: "menu/a-trapanisa.jpg" },

  /* ---------------- PIZZE LE VENETE ---------------- */
  { id: "bronsa-cuerta", categoria: "pizze-venete", nome: "Bronsa cuerta",
    descrizione: "Pomodoro, mozzarella, aglio, olio, peperoncino, salamino, gorgonzola e salsiccia",
    prezzo: 12.00, foto: "menu/bronsa-cuerta.jpg", tag: ["piccante"] },
  { id: "oce-oce", categoria: "pizze-venete", nome: "Oce Oce",
    descrizione: "Pomodoro, prosciutto cotto, Bufala e zucchine fritte (entrambe dopo cottura)",
    prezzo: 14.00, foto: "menu/oce-oce.jpg" },
  { id: "strafanto", categoria: "pizze-venete", nome: "Strafanto",
    descrizione: "Pomodoro, mozzarella, prosciutto cotto, crema di tartufo, carciofi e grana",
    prezzo: 12.00, foto: "menu/strafanto.jpg" },
  { id: "vecia", categoria: "pizze-venete", nome: "Vecia",
    descrizione: "Pomodoro, mozzarella, funghi chiodini, asiago e dopo cottura soppressa",
    prezzo: 10.00, foto: "menu/vecia.jpg" },
  { id: "onto", categoria: "pizze-venete", nome: "Onto",
    descrizione: "Pomodoro, mozzarella, peperoni, cipolla, porchetta e asiago",
    prezzo: 11.00, foto: "menu/onto.jpg" },
  { id: "scarsea", categoria: "pizze-venete", nome: "Scarsea",
    descrizione: "Mozzarella, salmone, olive taggiasche, philadelphia e cipolla",
    prezzo: 12.00, foto: "menu/scarsea.jpg" },
  { id: "selvadego", categoria: "pizze-venete", nome: "Selvadego",
    descrizione: "Pomodoro, mozzarella, salsiccia, patate lesse, pecorino e olive verdi",
    prezzo: 11.00, foto: "menu/selvadego.jpg" },
  { id: "rabalta", categoria: "pizze-venete", nome: "Rabaltà",
    descrizione: "Pomodoro, mozzarella, stracchino, dopo cottura zucchine fritte e bresaola",
    prezzo: 12.50, foto: "menu/rabalta.jpg" },
  { id: "baucca", categoria: "pizze-venete", nome: "Baucca",
    descrizione: "Mozzarella, gamberetti, dopo cottura pomodorini, rucola e mais",
    prezzo: 12.00, foto: "menu/baucca.jpg" },
  { id: "mona", categoria: "pizze-venete", nome: "Mona",
    descrizione: "Pomodoro, mozzarella, asparagi, uovo e pancetta in cottura",
    prezzo: 10.00, foto: "menu/mona.jpg" },
  { id: "indrio", categoria: "pizze-venete", nome: "Indrio",
    descrizione: "Mozzarella, verdure cotte, dopo cottura soppressa e burrata",
    prezzo: 12.00, foto: "menu/indrio.jpg" },

  /* ---------------- PIZZE LE VEGANE ---------------- */
  { id: "sebastian", categoria: "pizze-vegane", nome: "Sebastian",
    descrizione: "Pomodoro, pesto di basilico, carciofi, peperoni e pomodorino caramellato",
    prezzo: 11.00, foto: "menu/sebastian.jpg", tag: ["vegano"] },
  { id: "cinzia", categoria: "pizze-vegane", nome: "Cinzia",
    descrizione: "Pomodoro, funghi chiodini, dopo cottura rucola e noci",
    prezzo: 10.00, foto: "menu/cinzia.jpg", tag: ["vegano"] },
  { id: "adolfo", categoria: "pizze-vegane", nome: "Adolfo",
    descrizione: "Pomodoro, patate al forno, olive taggiasche, capperi, cipolla, rosmarino, funghi crudi e pomodorini",
    prezzo: 11.00, foto: "menu/adolfo.jpg", tag: ["vegano"] },
  { id: "mimmo", categoria: "pizze-vegane", nome: "Mimmo",
    descrizione: "Pomodoro, asparagi, zucchine, olive nere al forno, origano e pomodori secchi",
    prezzo: 10.00, foto: "menu/mimmo.jpg", tag: ["vegano"] },
  { id: "stefy", categoria: "pizze-vegane", nome: "Stefy",
    descrizione: "Pomodoro, melanzane, zucchine, peperoni, prezzemolo e aglio",
    prezzo: 9.50, foto: "menu/stefy.jpg", tag: ["vegano"] },
  { id: "sara", categoria: "pizze-vegane", nome: "Sara",
    descrizione: "Pomodoro, misto funghi, dopo cottura pistacchio e olio di tartufo",
    prezzo: 13.00, foto: "menu/sara.jpg", tag: ["vegano"] },
  { id: "rosalia", categoria: "pizze-vegane", nome: "Rosalia",
    descrizione: "Pomodoro, finocchietto selvatico, uvetta e pinoli",
    prezzo: 11.00, foto: "menu/rosalia.jpg", tag: ["vegano"] },

  /* ---------------- PIZZE LE NOVITÀ ---------------- */
  { id: "a-ciaula", categoria: "pizze-novita", nome: "A'ciaula",
    descrizione: "Pomodoro, mozzarella, pancetta, scamorza e dopo cottura zucchine fritte",
    prezzo: 13.00, foto: "menu/a-ciaula.jpg", tag: ["novita"] },
  { id: "a-quartara", categoria: "pizze-novita", nome: "A'quartara",
    descrizione: "Mozzarella, crema di zucca, funghi porcini, crema di formaggi e dopo cottura prosciutto crudo",
    prezzo: 13.00, foto: "menu/a-quartara.jpg", tag: ["novita"] },
  { id: "a-bagascia", categoria: "pizze-novita", nome: "A'bagascia",
    descrizione: "Mozzarella, gamberetti, salmone, philadelphia e aroma di arancia",
    prezzo: 13.00, foto: "menu/a-bagascia.jpg", tag: ["novita"] },
  { id: "m-bare", categoria: "pizze-novita", nome: "M'bare",
    descrizione: "Pomodoro, mozzarella, tonno, stracchino, uovo e piselli",
    prezzo: 10.00, foto: "menu/m-bare.jpg", tag: ["novita"] },
  { id: "u-tumazzu", categoria: "pizze-novita", nome: "U'tumazzu",
    descrizione: "Mozzarella, caciocavallo, asiago, primo sale, gorgonzola e marmellate a fantasia",
    prezzo: 13.00, foto: "menu/u-tumazzu.jpg", tag: ["novita"] },
  { id: "a-prescia", categoria: "pizze-novita", nome: "A'prescia",
    descrizione: "Mozzarella, peperoni, mais, patè d'olive, dopo cottura burrata e prosciutto crudo",
    prezzo: 13.00, foto: "menu/a-prescia.jpg", tag: ["novita"] },
  { id: "a-puveredda", categoria: "pizze-novita", nome: "A' Puveredda",
    descrizione: "Mozzarella, gorgonzola, cipolla, mortadella e grana",
    prezzo: 12.00, foto: "menu/a-puveredda.jpg", tag: ["novita"] },

  /* ---------------- MILINGIANA FRIUTA ---------------- */
  { id: "milingiana-1", categoria: "milingiana-friuta", nome: "Milingiana 1",
    descrizione: "Pizza pomodoro, mozzarella, melanzane fritte, dopo cottura ricotta salata a scaglie e basilico",
    prezzo: 10.00, foto: "menu/milingiana-1.jpg" },
  { id: "milingiana-2", categoria: "milingiana-friuta", nome: "Milingiana 2",
    descrizione: "Pizza pomodoro, mozzarella, melanzane fritte, salsiccia, dopo cottura formaggio primo sale",
    prezzo: 11.00, foto: "menu/milingiana-2.jpg" },
  { id: "milingiana-3", categoria: "milingiana-friuta", nome: "Milingiana 3",
    descrizione: "Pizza pomodoro, mozzarella, melanzane fritte, basilico e prosciutto cotto",
    prezzo: 10.00, foto: "menu/milingiana-3.jpg" },
  { id: "milingiana-4", categoria: "milingiana-friuta", nome: "Milingiana 4",
    descrizione: "Pizza pomodoro, melanzane fritte, salamino, dopo cottura mozzarella di bufala",
    prezzo: 11.00, foto: "menu/milingiana-4.jpg" },
  { id: "milingiana-5", categoria: "milingiana-friuta", nome: "Milingiana 5",
    descrizione: "Pizza pomodoro, mozzarella, melanzane fritte, grana e dopo cottura porchetta",
    prezzo: 11.00, foto: "menu/milingiana-5.jpg" },
  { id: "milingiana-6", categoria: "milingiana-friuta", nome: "Milingiana 6",
    descrizione: "Pizza pomodoro, mozzarella, melanzane fritte, olive nere denocciolate, pomodorini e funghi freschi",
    prezzo: 10.00, foto: "menu/milingiana-6.jpg" },
  { id: "milingiana-7", categoria: "milingiana-friuta", nome: "Milingiana 7",
    descrizione: "Pizza bianca, mozzarella, melanzane fritte, crema di zucca, funghi chiodini e dopo cottura ricotta salata",
    prezzo: 12.50, foto: "menu/milingiana-7.jpg" },

  /* ---------------- I PATAT ---------------- */
  { id: "i-patat-1", categoria: "i-patat", nome: "I patat 1",
    descrizione: "Pomodoro, mozzarella e patate fritte",
    prezzo: 8.50, foto: "menu/i-patat-1.jpg" },
  { id: "i-patat-2", categoria: "i-patat", nome: "I patat 2",
    descrizione: "Pomodoro, mozzarella, patate fritte e prosciutto cotto",
    prezzo: 9.50, foto: "menu/i-patat-2.jpg" },
  { id: "i-patat-3", categoria: "i-patat", nome: "I patat 3",
    descrizione: "Pomodoro, mozzarella, patate fritte e wurstel",
    prezzo: 9.50, foto: "menu/i-patat-3.jpg" },
  { id: "i-patat-4", categoria: "i-patat", nome: "I patat 4",
    descrizione: "Pomodoro, mozzarella, patate al forno, gorgonzola e funghi porcini",
    prezzo: 10.00, foto: "menu/i-patat-4.jpg" },
  { id: "i-patat-5", categoria: "i-patat", nome: "I patat 5",
    descrizione: "Pomodoro, mozzarella, patate al forno, scamorza e pancetta",
    prezzo: 10.00, foto: "menu/i-patat-5.jpg" },
  { id: "i-patat-6", categoria: "i-patat", nome: "I patat 6",
    descrizione: "Pomodoro, mozzarella, patate al forno, grana, salsiccia e funghi crudi",
    prezzo: 11.00, foto: "menu/i-patat-6.jpg" },
  { id: "i-patat-7", categoria: "i-patat", nome: "I patat 7",
    descrizione: "Mozzarella, peperoni, philadelphia, patate lesse e mortadella",
    prezzo: 12.00, foto: "menu/i-patat-7.jpg" },
  { id: "i-patat-8", categoria: "i-patat", nome: "I patat 8",
    descrizione: "Mozzarella, patate lesse, salmone, burrata e asparagi",
    prezzo: 12.00, foto: "menu/i-patat-8.jpg" },
  { id: "i-patat-9", categoria: "i-patat", nome: "I patat 9",
    descrizione: "Pomodoro, mozzarella, patate lesse, 'nduja, carciofi e brie",
    prezzo: 12.00, foto: "menu/i-patat-9.jpg", tag: ["piccante"] },

  /* ---------------- CALZONE ---------------- */
  { id: "calzone-farcito", categoria: "calzone", nome: "Calzone farcito",
    descrizione: "Mozzarella, funghi, carciofi, prosciutto cotto e dopo cottura salsa di pomodoro",
    prezzo: 9.00, foto: "menu/calzone-farcito.jpg" },

  /* ---------------- CALZONCINI ---------------- */
  { id: "l-hamburgherino", categoria: "calzoncini", nome: "L'hamburgherino",
    descrizione: "Salsiccia, Cipolla Caramellata, Brie, Pomodoro Fresco.",
    prezzo: 4.50, foto: "menu/l-hamburgherino.jpg" },
  { id: "calzoncino-10", categoria: "calzoncini", nome: "Calzoncino 10",
    descrizione: "Mozzarella, wurstel, patate al forno e salsa rosa",
    prezzo: 3.50, foto: "menu/calzoncino-10.jpg" },
  { id: "calzoncino-11", categoria: "calzoncini", nome: "Calzoncino 11",
    descrizione: "Besciamella, salsiccia, pistacchio e philadelphia",
    prezzo: 3.50, foto: "menu/calzoncino-11.jpg" },
  { id: "calzoncino-4", categoria: "calzoncini", nome: "Calzoncino 4",
    descrizione: "Pomodoro, mozzarella, melanzane fritte e salsiccia",
    prezzo: 3.50, foto: "menu/calzoncino-4.jpg" },
  { id: "calzoncino-1", categoria: "calzoncini", nome: "Calzoncino 1",
    descrizione: "Pomodoro, mozzarella, prosciutto e funghi",
    prezzo: 3.50, foto: "menu/calzoncino-1.jpg" },
  { id: "calzoncino-3", categoria: "calzoncini", nome: "Calzoncino 3",
    descrizione: "Pomodoro, mozzarella e melanzane fritte",
    prezzo: 3.50, foto: "menu/calzoncino-3.jpg" },
  { id: "calzoncino-5", categoria: "calzoncini", nome: "Calzoncino 5",
    descrizione: "Pomodoro fresco, mozzarella e origano",
    prezzo: 3.50, foto: "menu/calzoncino-5.jpg" },
  { id: "calzoncino-2", categoria: "calzoncini", nome: "Calzoncino 2",
    descrizione: "Pomodoro, mozzarella, prosciutto e origano",
    prezzo: 3.50, foto: "menu/calzoncino-2.jpg" },
  { id: "calzoncino-6", categoria: "calzoncini", nome: "Calzoncino 6",
    descrizione: "Mozzarella, peperoni, zucchine e gorgonzola",
    prezzo: 3.50, foto: "menu/calzoncino-6.jpg" },
  { id: "calzoncino-9", categoria: "calzoncini", nome: "Calzoncino 9",
    descrizione: "Ricotta e spinaci",
    prezzo: 3.50, foto: "menu/calzoncino-9.jpg" },
  { id: "calzoncino-12", categoria: "calzoncini", nome: "Calzoncino 12",
    descrizione: "Ricotta, Salamino, Patate a Forno.",
    prezzo: 3.50, foto: "menu/calzoncino-12.jpg" },
  { id: "calzoncino-8", categoria: "calzoncini", nome: "Calzoncino 8",
    descrizione: "Pomodoro, mozzarella, spinaci e salsiccia",
    prezzo: 3.50, foto: "menu/calzoncino-8.jpg" },

  /* ---------------- CALZONI FRITTI ---------------- */
  { id: "calzone-fritto-3", categoria: "calzoni-fritti", nome: "Calzone fritto 3",
    descrizione: "Pomodoro mozzarella e basilico",
    prezzo: 4.00, foto: "menu/calzone-fritto-3.jpg" },
  { id: "calzone-fritto-1", categoria: "calzoni-fritti", nome: "Calzone fritto 1",
    descrizione: "Mozzarella e prosciutto cotto",
    prezzo: 4.00, foto: "menu/calzone-fritto-1.jpg" },
  { id: "calzone-fritto-2", categoria: "calzoni-fritti", nome: "Calzone fritto 2",
    descrizione: "Mozzarella e salamino piccante",
    prezzo: 4.00, foto: "menu/calzone-fritto-2.jpg", tag: ["piccante"] },

  /* ---------------- PANINI ALLA PIASTRA ---------------- */
  { id: "panino-2", categoria: "panini", nome: "Panino 2",
    descrizione: "Wurstel, patatine e formaggio",
    prezzo: 6.00, foto: "menu/panino-2.jpg" },
  { id: "panino-3", categoria: "panini", nome: "Panino 3",
    descrizione: "Prosciutto cotto, formaggio, patatine e funghi",
    prezzo: 7.50, foto: "menu/panino-3.jpg" },
  { id: "panino-1", categoria: "panini", nome: "Panino 1",
    descrizione: "Salsiccia, patatine, formaggi e cipolla",
    prezzo: 7.50, foto: "menu/panino-1.jpg" },

  /* ---------------- ARANCINI ---------------- */
  { id: "arancino-1", categoria: "arancini", nome: "Arancino 1",
    descrizione: "Al ragù, piselli e formaggio",
    prezzo: 3.50, foto: "menu/arancino-1.jpg" },
  { id: "arancino-2", categoria: "arancini", nome: "Arancino 2",
    descrizione: "Melanzane fritte, pomodoro e ricotta salata",
    prezzo: 3.50, foto: "menu/arancino-2.jpg" },
  { id: "arancino-3", categoria: "arancini", nome: "Arancino 3",
    descrizione: "Speck, pistacchio, formaggio e besciamella",
    prezzo: 3.50, foto: "menu/arancino-3.jpg" },
  { id: "arancino-4", categoria: "arancini", nome: "Arancino 4",
    descrizione: "Prosciutto, besciamella e formaggio",
    prezzo: 3.50, foto: "menu/arancino-4.jpg" },
  { id: "arancino-5", categoria: "arancini", nome: "Arancino 5",
    descrizione: "Funghi, crema di tartufo e besciamella",
    prezzo: 3.50, foto: "menu/arancino-5.jpg" },
  { id: "arancino-6", categoria: "arancini", nome: "Arancino 6",
    descrizione: "Spinaci e philadelphia",
    prezzo: 3.50, foto: "menu/arancino-6.jpg" },
  { id: "arancino-7", categoria: "arancini", nome: "Arancino 7",
    descrizione: "Gorgonzola, peperoni e besciamella",
    prezzo: 3.50, foto: "menu/arancino-7.jpg" },
  { id: "arancino-8", categoria: "arancini", nome: "Arancino 8",
    descrizione: "Salmone affumicato e besciamella",
    prezzo: 3.50, foto: "menu/arancino-8.jpg" },
  { id: "arancino-9", categoria: "arancini", nome: "Arancino 9",
    descrizione: "Besciamella, mortadella, pistacchio e formaggio",
    prezzo: 3.50, foto: "menu/arancino-9.jpg" },
  { id: "arancino-10", categoria: "arancini", nome: "Arancino 10",
    descrizione: "Acciughe, primo sale, olive nere e besciamella",
    prezzo: 3.50, foto: "menu/arancino-10.jpg" },
  { id: "arancino-11", categoria: "arancini", nome: "Arancino 11",
    descrizione: "Ragù di salumi, formaggio e 'nduja",
    prezzo: 3.50, foto: "menu/arancino-11.jpg", tag: ["piccante"] },
  { id: "arancino-12", categoria: "arancini", nome: "Arancino 12",
    descrizione: "Salsiccia, philadelphia, besciamella e pistacchio",
    prezzo: 3.50, foto: "menu/arancino-12.jpg" },
  { id: "arancino-13", categoria: "arancini", nome: "Arancino 13",
    descrizione: "Prosecco, formaggio, mazzancolle, scorza di limone e besciamella",
    prezzo: 4.00, foto: "menu/arancino-13.jpg" },
  { id: "arancino-14", categoria: "arancini", nome: "Arancino 14",
    descrizione: "Ragù d'anatra e formaggio",
    prezzo: 4.00, foto: "menu/arancino-14.jpg" },
  { id: "arancino-15", categoria: "arancini", nome: "Arancino 15",
    descrizione: "Pollo curry",
    prezzo: 4.00, foto: "menu/arancino-15.jpg" },
  { id: "arancino-16", categoria: "arancini", nome: "Arancino 16",
    descrizione: "Pesce spada, melanzane fritte, mentuccia, pomodoro caramellato.",
    prezzo: 4.00, foto: "menu/arancino-16.jpg" },

  /* ---------------- FRITTI ---------------- */
  { id: "patatine-fritte", categoria: "fritti", nome: "Patatine fritte",
    prezzo: 3.50, foto: "menu/patatine-fritte.jpg" },
  { id: "crocche", categoria: "fritti", nome: "Crocchè",
    prezzo: 4.00, foto: "menu/crocche.jpg" },
  { id: "jalapenos", categoria: "fritti", nome: "Jalapenos",
    prezzo: 4.50, foto: "menu/jalapenos.jpg", tag: ["piccante"] },
  { id: "olive-ascolane", categoria: "fritti", nome: "Olive ascolane",
    prezzo: 4.00, foto: "menu/olive-ascolane.jpg" },
  { id: "mozzarelline", categoria: "fritti", nome: "Mozzarelline",
    prezzo: 4.00, foto: "menu/mozzarelline.jpg" },

  /* ---------------- PANE E PANELLE ---------------- */
  { id: "panelle-6-pezzi", categoria: "pane-panelle", nome: "Panelle 6 pezzi",
    descrizione: "Sale, pepe e limone",
    prezzo: 5.00, foto: "menu/panelle-6-pezzi.jpg" },
  { id: "pane-e-panelle-condito", categoria: "pane-panelle", nome: "Pane e panelle condito",
    descrizione: "Sale, pepe e limone",
    prezzo: 5.50, foto: "menu/pane-e-panelle-condito.jpg" },
  { id: "pane-e-panelle-con-mortadella-e-fettine-di-limone", categoria: "pane-panelle", nome: "Pane e panelle con mortadella e fettine di limone",
    descrizione: "Sale, pepe e limone",
    prezzo: 6.00, foto: "menu/pane-e-panelle-con-mortadella-e-fettine-di-limone.jpg" },

  /* ---------------- SPECIALITÀ SICILIANE ---------------- */
  { id: "anelletti-palermitani-al-forno", categoria: "specialita", nome: "Anelletti palermitani al forno",
    descrizione: "Pasta, ragù, mozzarella, melanzane fritte, pangrattato",
    prezzo: 7.50, foto: "menu/anelletti-palermitani-al-forno.jpg" },
  { id: "sfincione", categoria: "specialita", nome: "Sfincione",
    descrizione: "Pizza alta con pomodoro, cipolla, acciughe, pan grattato, primo sale, origano e pecorino",
    prezzo: 4.00, foto: "menu/sfincione.jpg" },
  { id: "rollo-di-wurstel", categoria: "specialita", nome: "Rollò di wurstel",
    prezzo: 3.50, foto: "menu/rollo-di-wurstel.jpg" },
  { id: "parmigiana", categoria: "specialita", nome: "Parmigiana",
    descrizione: "Melanzane fritte, pomodoro, basilico e grana 250gr",
    prezzo: 6.00, foto: "menu/parmigiana.jpg" },
  { id: "cipollina", categoria: "specialita", nome: "Cipollina",
    descrizione: "Pasta sfoglia, mozzarella, pomodoro, cipolla, olive nere e prosciutto cotto",
    prezzo: 4.50, foto: "menu/cipollina.jpg" },
  { id: "ravazzata-al-ragu-e-piselli", categoria: "specialita", nome: "Ravazzata al ragù e piselli",
    prezzo: 4.00, foto: "menu/ravazzata-al-ragu-e-piselli.jpg" },

  /* ---------------- DOLCI ---------------- */
  { id: "pizza-tiramisu", categoria: "dolci", nome: "Pizza tiramisù",
    prezzo: 12.00, foto: "menu/pizza-tiramisu.jpg" },
  { id: "cannolo-siciliano", categoria: "dolci", nome: "Cannolo siciliano",
    descrizione: "Con ricotta di pecora",
    prezzo: 4.00, foto: "menu/cannolo-siciliano.jpg" },
  { id: "cannolo-siciliano-al-pistacchio", categoria: "dolci", nome: "Cannolo siciliano al pistacchio",
    descrizione: "Con ricotta di pecora e pistacchio",
    prezzo: 5.00, foto: "menu/cannolo-siciliano-al-pistacchio.jpg" },
  { id: "cassatina-palermitana", categoria: "dolci", nome: "Cassatina palermitana",
    prezzo: 4.00, foto: "menu/cassatina-palermitana.jpg" },

  /* ---------------- PIZZE DOLCI ---------------- */
  { id: "pizza-alla-nutella", categoria: "pizze-dolci", nome: "Pizza alla nutella",
    descrizione: "Nutella e zucchero a velo",
    prezzo: 6.00, foto: "menu/pizza-alla-nutella.jpg" },
  { id: "pizza-alla-nutella-e-pistacchio", categoria: "pizze-dolci", nome: "Pizza alla nutella e pistacchio",
    descrizione: "Nutella, zucchero a velo e granella di pistacchio",
    prezzo: 7.50, foto: "menu/pizza-alla-nutella-e-pistacchio.jpg" },

  /* ---------------- BEVANDE ---------------- */
  { id: "coca-cola-1lt", categoria: "bevande", nome: "Coca-Cola 1lt",
    prezzo: 4.00, foto: "menu/coca-cola-1lt.jpg" },
  { id: "coca-cola-zero-33cl", categoria: "bevande", nome: "Coca-Cola Zero 33cl",
    prezzo: 3.00, foto: "menu/coca-cola-zero-33cl.jpg" },
  { id: "coca-cola-33cl", categoria: "bevande", nome: "Coca-Cola 33cl",
    prezzo: 3.00, foto: "menu/coca-cola-33cl.jpg" },
  { id: "acqua-naturale-50cl", categoria: "bevande", nome: "Acqua naturale 50cl",
    prezzo: 1.50, foto: "menu/acqua-naturale-50cl.jpg" },
  { id: "fanta-33cl", categoria: "bevande", nome: "Fanta 33cl",
    prezzo: 3.00, foto: "menu/fanta-33cl.jpg" },
  { id: "acqua-frizzante-50cl", categoria: "bevande", nome: "Acqua frizzante 50cl",
    prezzo: 1.50, foto: "menu/acqua-frizzante-50cl.jpg" },
  { id: "sprite-33cl", categoria: "bevande", nome: "Sprite 33cl",
    prezzo: 3.00, foto: "menu/sprite-33cl.jpg" },
  { id: "te-al-limone-33cl", categoria: "bevande", nome: "Tè al limone 33cl",
    prezzo: 3.00, foto: "menu/te-al-limone-33cl.jpg" },
  { id: "te-alla-pesca-33cl", categoria: "bevande", nome: "Tè alla pesca 33cl",
    prezzo: 3.00, foto: "menu/te-alla-pesca-33cl.jpg" },

  /* ---------------- BIRRE ---------------- */
  { id: "moretti-66cl", categoria: "birre", nome: "Moretti 66cl",
    prezzo: 4.50, foto: "menu/moretti-66cl.jpg" },
  { id: "a-miriusa", categoria: "birre", nome: "A' Miriusa",
    descrizione: "Birra siciliana IPA",
    prezzo: 5.00, foto: "menu/a-miriusa.jpg" },
  { id: "a-smaniusa", categoria: "birre", nome: "A' Smaniusa",
    descrizione: "Birra siciliana Bianca al Pepe Rosa",
    prezzo: 5.00, foto: "menu/a-smaniusa.jpg" },
  { id: "a-licca", categoria: "birre", nome: "A' Licca",
    descrizione: "Birra siciliana Bionda Doppio Malto",
    prezzo: 5.00, foto: "menu/a-licca.jpg" },
  { id: "messina-33cl", categoria: "birre", nome: "Messina 33cl",
    prezzo: 3.50, foto: "menu/messina-33cl.jpg" },
  { id: "ceres-33cl", categoria: "birre", nome: "Ceres 33cl",
    prezzo: 4.50, foto: "menu/ceres-33cl.jpg" },
  { id: "a-raggiata", categoria: "birre", nome: "A' Raggiata",
    descrizione: "Birra siciliana Rossa",
    prezzo: 5.00, foto: "menu/a-raggiata.jpg" },
  { id: "messina-cristalli-di-sale-50cl", categoria: "birre", nome: "Messina Cristalli di Sale 50cl",
    prezzo: 4.50, foto: "menu/messina-cristalli-di-sale-50cl.jpg" },

  /* ---------------- T-SHIRT ---------------- */
  { id: "menza-parola", categoria: "t-shirt", nome: "Menza parola",
    descrizione: "T-shirt manica corta nera personalizzata. Uomo/donna, taglie S, M, L, XL.",
    prezzo: 20.00, foto: "menu/menza-parola.jpg" },

  /* ---------------- MEAL DEALS ---------------- */
  { id: "scegli-il-menu", categoria: "meal-deals", nome: "Scegli il Menù",
    prezzo: 19.50, foto: "menu/scegli-il-menu.jpg" },
];

/* Etichette dei tag mostrate sulle card — modifica qui i testi */
const TAG_LABEL = {
  vegetariano: { testo: 'Veg', classe: 'tag--veg' },
  vegano:      { testo: 'Vegano', classe: 'tag--vegan' },
  piccante:    { testo: 'Piccante', classe: 'tag--hot' },
  novita:      { testo: 'Novità', classe: 'tag--new' },
};

window.CAMAFFARE_MENU = { CATEGORIE, PRODOTTI, TAG_LABEL };
